name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

# Pages デプロイに必要な権限設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # テスト（CI）ジョブ
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint

  # デプロイ（CD）ジョブ
  deploy:
    needs: test # テストが成功した時のみ実行される
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # ルートディレクトリを公開対象にする

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
